export function getConfigureHtml(manifest, currentHost, currentConfigEncoded) {
    const catalogCheckboxes = manifest.catalogs
        .filter(c => c.id !== 'search')
        .map(c => [
            '<label class="flex items-center justify-between p-3.5 bg-slate-800/60 hover:bg-slate-800 rounded-xl border border-slate-700/60 cursor-pointer transition">',
            '    <span class="text-sm font-medium text-slate-200">' + c.name + '</span>',
            '    <input type="checkbox" id="cat_' + c.id + '" checked class="w-5 h-5 rounded accent-amber-500 cursor-pointer config-checkbox">',
            '</label>'
        ].join('\n')).join('\n');

    const configJson = currentConfigEncoded ? decodeURIComponent(currentConfigEncoded) : '{}';

    return [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '    <meta charset="UTF-8">',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '    <title>Cinemeta of Audiobooks - Configuration</title>',
        '    <script src="https://cdn.tailwindcss.com"></script>',
        '</head>',
        '<body class="bg-slate-950 text-slate-100 min-h-screen py-10 px-4 flex justify-center">',
        '    <div class="max-w-3xl w-full bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-10 shadow-2xl space-y-8">',
        '        <div class="flex items-center gap-4 border-b border-slate-800 pb-6">',
        '            <div class="w-14 h-14 bg-amber-500/20 border border-amber-500/30 rounded-2xl flex items-center justify-center text-3xl">🎧</div>',
        '            <div>',
        '                <h1 class="text-2xl font-bold text-white tracking-tight">Cinemeta of Audiobooks</h1>',
        '                <p class="text-sm text-slate-400">Customize your discover rows, pinned creators, and playback style</p>',
        '            </div>',
        '        </div>',
        '        <!-- Section 1: Pinned Custom Rows -->',
        '        <div class="space-y-4">',
        '            <h2 class="text-base font-semibold text-amber-400 uppercase tracking-wider text-xs">1. Pinned Custom Rows (Creates Home Board Rows)</h2>',
        '            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">',
        '                <div>',
        '                    <label class="block text-sm font-medium text-slate-300 mb-1">Pinned Author</label>',
        '                    <input type="text" id="pinned_author" placeholder="e.g., Stephen King, Neil Gaiman" class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2.5 text-sm text-white focus:ring-2 focus:ring-amber-500 outline-none config-input">',
        '                </div>',
        '                <div>',
        '                    <label class="block text-sm font-medium text-slate-300 mb-1">Pinned Narrator</label>',
        '                    <input type="text" id="pinned_narrator" placeholder="e.g., Stephen Fry, Scott Brick" class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2.5 text-sm text-white focus:ring-2 focus:ring-amber-500 outline-none config-input">',
        '                </div>',
        '            </div>',
        '        </div>',
        '        <!-- Section 2: Catalogue Rows -->',
        '        <div class="space-y-4">',
        '            <h2 class="text-base font-semibold text-amber-400 uppercase tracking-wider text-xs">2. Catalogue Rows (Enable / Disable)</h2>',
        '            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">',
        catalogCheckboxes,
        '            </div>',
        '        </div>',
        '        <!-- Section 3: Playback & Content Settings -->',
        '        <div class="space-y-4">',
        '            <h2 class="text-base font-semibold text-amber-400 uppercase tracking-wider text-xs">3. Playback & Content Filters</h2>',
        '            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">',
        '                <div>',
        '                    <label class="block text-sm font-medium text-slate-300 mb-1">Playback Style</label>',
        '                    <select id="playback_style" class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2.5 text-sm text-white focus:ring-2 focus:ring-amber-500 outline-none">',
        '                        <option value="both">Both (Chapters & Complete Audio)</option>',
        '                        <option value="chapters">Chapters Only (Track Navigation)</option>',
        '                        <option value="single_file">Single-File Preferred (Continuous Audio on Top)</option>',
        '                    </select>',
        '                </div>',
        '                <div>',
        '                    <label class="block text-sm font-medium text-slate-300 mb-1">Language Filter</label>',
        '                    <select id="language" class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2.5 text-sm text-white focus:ring-2 focus:ring-amber-500 outline-none">',
        '                        <option value="all">All Languages</option>',
        '                        <option value="en">English Only</option>',
        '                        <option value="es">Spanish</option>',
        '                        <option value="fr">French</option>',
        '                        <option value="de">German</option>',
        '                    </select>',
        '                </div>',
        '            </div>',
        '            <div class="space-y-3 pt-2">',
        '                <label class="flex items-center justify-between p-3.5 bg-slate-800/60 hover:bg-slate-800 rounded-xl border border-slate-700/60 cursor-pointer transition">',
        '                    <div>',
        '                        <div class="text-sm font-medium text-slate-200">Hide Abridged Versions</div>',
        '                        <div class="text-xs text-slate-400">Only show complete, unabridged recordings</div>',
        '                    </div>',
        '                    <input type="checkbox" id="hide_abridged" class="w-5 h-5 rounded accent-amber-500 cursor-pointer config-checkbox">',
        '                </label>',
        '                <label class="flex items-center justify-between p-3.5 bg-slate-800/60 hover:bg-slate-800 rounded-xl border border-slate-700/60 cursor-pointer transition">',
        '                    <div>',
        '                        <div class="text-sm font-medium text-slate-200">Public Domain Only</div>',
        '                        <div class="text-xs text-slate-400">Strictly show books with guaranteed free audio</div>',
        '                    </div>',
        '                    <input type="checkbox" id="public_domain_only" class="w-5 h-5 rounded accent-amber-500 cursor-pointer config-checkbox">',
        '                </label>',
        '                <label class="flex items-center justify-between p-3.5 bg-slate-800/60 hover:bg-slate-800 rounded-xl border border-slate-700/60 cursor-pointer transition">',
        '                    <div>',
        '                        <div class="text-sm font-medium text-slate-200">Hide Explicit Content</div>',
        '                        <div class="text-xs text-slate-400">Filter out mature/explicit tagged audiobooks</div>',
        '                    </div>',
        '                    <input type="checkbox" id="hide_explicit" class="w-5 h-5 rounded accent-amber-500 cursor-pointer config-checkbox">',
        '                </label>',
        '            </div>',
        '        </div>',
        '        <!-- Action Buttons -->',
        '        <div class="pt-6 border-t border-slate-800 flex flex-col sm:flex-row gap-3">',
        '            <button onclick="installAddon(\'stremio\')" class="flex-1 py-4 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-2xl shadow-lg shadow-amber-500/20 transition text-center cursor-pointer">',
        '                Update / Install on Stremio',
        '            </button>',
        '            <button onclick="installAddon(\'nuvio\')" class="flex-1 py-4 bg-slate-800 hover:bg-slate-700 text-white font-semibold rounded-2xl border border-slate-700 transition text-center cursor-pointer">',
        '                Copy for Nuvio',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <script>',
        '        // Edit-Mode Pre-Filling: Load saved settings without regex bugs',
        '        const existingConfig = ' + JSON.stringify(configJson) + ';',
        '        window.addEventListener("DOMContentLoaded", () => {',
        '            try {',
        '                const config = JSON.parse(existingConfig);',
        '                document.querySelectorAll(".config-checkbox").forEach(cb => {',
        '                    if (config[cb.id] !== undefined) {',
        '                        cb.checked = config[cb.id];',
        '                    }',
        '                });',
        '                document.querySelectorAll(".config-input").forEach(inp => {',
        '                    if (config[inp.id]) {',
        '                        inp.value = config[inp.id];',
        '                    }',
        '                });',
        '                if (config.playback_style) document.getElementById("playback_style").value = config.playback_style;',
        '                if (config.language) document.getElementById("language").value = config.language;',
        '            } catch (e) {}',
        '        });',
        '        function generateConfig() {',
        '            const config = {};',
        '            document.querySelectorAll(".config-checkbox").forEach(cb => {',
        '                config[cb.id] = cb.checked;',
        '            });',
        '            const pinnedAuth = document.getElementById("pinned_author").value.trim();',
        '            if (pinnedAuth) config.pinned_author = pinnedAuth;',
        '            const pinnedNarr = document.getElementById("pinned_narrator").value.trim();',
        '            if (pinnedNarr) config.pinned_narrator = pinnedNarr;',
        '            config.playback_style = document.getElementById("playback_style").value;',
        '            config.language = document.getElementById("language").value;',
        '            return encodeURIComponent(JSON.stringify(config));',
        '        }',
        '        function installAddon(client) {',
        '            const cfg = generateConfig();',
        '            const url = window.location.origin + "/" + cfg + "/manifest.json";',
        '            if (client === "stremio") {',
        '                window.location.href = url.replace(/^http/, "stremio");',
        '            } else {',
        '                navigator.clipboard.writeText(url).then(() => {',
        '                    alert("Copied configured manifest URL to clipboard!\\n\\nPaste it into Nuvio Addon Manager:\\n" + url);',
        '                });',
        '            }',
        '        }',
        '    </script>',
        '</body>',
        '</html>'
    ].join('\n');
}
